import { lazy } from 'react'

export const Privacy = lazy(() => import('views/PrivacyTerms/PrivacyTerms'))
export const License = lazy(() => import('views/PrivacyTerms/License'))
export const Terms_C = lazy(() => import('views/PrivacyTerms/TermsConditions'))
export const Dashboard = lazy(() => import('views/Dashboard/Dashboard'))
export const NomineeList = lazy(() => import('views/Nominee/NomineeList'))
export const Spends = lazy(() => import('views/Spends/SpendsList'))
export const Vault = lazy(() => import('views/DocumentVault/DocumentVault'))
export const PwdVault = lazy(() => import('views/PasswordVault/PasswordVault'))
export const Diary = lazy(() => import('views/Diary/Diary'))
export const MailConfirm = lazy(() => import('views/Login/MailConfirm'))
export const Portfolio = lazy(() => import('views/Portfolio/Portfolio'))
export const Sender = lazy(() => import('views/ContactUs/Sender'))
export const AddLiability = lazy(() => import('views/Liability/Liability'))
export const UpdateProfile = lazy(() => import('views/user/Edit'))
export const Subscription = lazy(() => import('views/user/PaymentsIntegrated'))
export const home = lazy(() => import('views/LandingPage/LandingPage'))
export const AddAssets = lazy(() => import('views/Assets/Assets'))
